name 'jira'
maintainer 'Marcelo Mandolesi'
maintainer_email 'mmandolesi@gmail.com'
license 'all_rights'
description 'Installs/Configures Atlassian Jira'
long_description 'Installs/Configures Atlassian Jira'
version '0.3.0'
